---
language: node_js
node_js: "lts/*"

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-unstable

cache:
  yarn: true
  directories:
    - node_modules
    - bower_components
    - .eslintcache
    - $HOME/.cache/bower
    - $HOME/cc

env:
  global:
    - CC_TEST_REPORTER_ID=e0a829720254a3290ad709fb6e986879956db83fd864bd395d5389969c7d3e84
    - SAUCE_USERNAME=nomego
    - secure: CnP6QUvFX7Bkqb/lNm/N9KMksLBuuN5Rp88LLp9mNAZ+P/Eufv392UoJLyOeaixm7WK/yY5XdkY/UoL8cClo6NsXGunQ4J0mWbdVu7ti0CN7JrnFJmV/S7bT8top25nHI2bfdchKMGD4bzIIFiMRup2Zt1YKP5AGK+WVq08PdMgP2iDv3Lv2MoTaIDBgI3EhKsQ6y5pIV07/Q6pCuJRPlyyCNvlHe7Adfgv2w153yKAkJpL7lPIEmt3qsCzPuhI02CahgmZS7Lbo4SD0jofOOktDm9Tdb7S1jf0wYUEK6p1NP16YT8glm+iUAD/LJNwq0UlSPpZV4Wb8LJC2AmnIH5OmiS/EWhvd8Mt8wNL0B1aDAS0Iajdddp0dx1kgzXppsbaXMiH/ruwqXi1lNrwuqaV04RRwRbzsv1e18/vplWUmullN9IMA/SDJaX8fC/n/d9ugpM0eDJQXkos9zvEG3O14A7pcb1SjSWIkO+3w8NdtfifjVtY+gItA8imqmSp3SME/mUJE3aOkXzQ07r7TIixAXvSL8J9o6ZKNB+oKVRZFf3t9gWQYsgdckYxoBOAccUh7fLsbRC8SKZTD+fUH8T4t7pP0wYolQpwm6hIb0gKYGp2x7sSaNhJ6U3GI1OKIQZfHEpt3Dm798t21hiBzIOuBMnW6Jtv61m0U8onw0bo=
    - NEO_CC_URL=https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    - NEO_CC=$HOME/cc/cc-test-reporter
    - LAUNCHPAD_CHROME=/usr/bin/google-chrome-unstable

before_script:
  - yarn lint
  - ([[ -e $NEO_CC ]] || curl -L $NEO_CC_URL > $NEO_CC) && chmod +x $NEO_CC
  - $NEO_CC before-build

script:
  - yarn test $([ -z "$SAUCE_ACCESS_KEY" ] && echo "--skip-plugin sauce")
  - $NEO_CC after-build --exit-code $TRAVIS_TEST_RESULT

notifications:
  slack:
    secure: IXGpFVUOifc5qJV2wNyHQOj+AKF6rSIcK0xPJW+djc2Bwo1wIVp9q2F0MeQHYxybTrjD5UcMo7333zdNZiR5hsyuNJ451J8YnHpFpansgk6cGa7gD2/eoIVfcNUh0yDLqCXgLawhVY0pWuDACVrFVhny2N/1HL2qzPGi2ZVIcrx104vFy86z1SRBMgxqmxO1TNljnJ2qsYQS20SdqBOFw3F7/D6xtblkHPjw0V4z7VzYUByh+1tmvPwvJ/HB3RWuO6W3sDCXSObe+Im9EKcQy4cDOOLj7xor/78rCmN9wSfjyb1s7kFuDdjpVR7XjrMJDLkJzLNNUxPzKNVio921WcZLYcW7HGOeOZn618l9effYCoo0PZuzijNNeDwQL2be6Ey0hF0vwYb1Y/o7n/+AF2x9zEaiHMK5RIsUfPl6M7+8nzrJ1Xk4eAhwgIcqhj9wIJqXvi0jxYP+gcluYgSWEklN+T5nYrBHLemSp2YbRrU2JSMbcZWG5TcRLPYIxt3gYRu5n9ZjaFHjMO/Em8vOg1pwAAWzJfJVL2pYc7mGmJLR1NKGl/rrDCHV65mRz9Y4bVG1jNRnfkqlCINkTGG4WDrn4SOP8vpMl0g8xY8Vt0IWHwU6MUqYKHU+NKhuizsM3TyeWjyfMZq9lI0YaaHiYBhsC+Br4F4kpQWBVz5gIZk=
